//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVICIO.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int Id { get; set; }
        public decimal Nota { get; set; }
        public System.DateTime FechaCalificacion { get; set; }
        public Nullable<int> IdEstudiante { get; set; }
        public Nullable<int> IdCurso { get; set; }

        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
    }
}
