//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVICIO.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        public int Id { get; set; }
        public Nullable<int> IdPago { get; set; }
        public Nullable<int> IdCurso { get; set; }
        public int ValorUnitario { get; set; }
        public int Cantidad { get; set; }
        [JsonIgnore]
        public virtual Curso Curso { get; set; }
        [JsonIgnore]
        public virtual Pago Pago { get; set; }
    }
}
