//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVICIO.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Sancion
    {
        public int Id { get; set; }
        public string Motivo { get; set; }
        public System.DateTime FechaSancion { get; set; }
        public int Duracion { get; set; }
        public Nullable<int> IdEstudiante { get; set; }

        [JsonIgnore]
        public virtual Estudiante Estudiante { get; set; }
    }
}
